apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: sfa
type: Opaque
stringData:
  APP_KEY: "base64:6DxwTaX1yeG7JfY42Rs8ibC8hbSCRlGoPkXIsUQ0KVk="
  JWT_SECRET: "vdiWdydatGmN7t0JvVzX0ICPaIA2bGxMKG0Jc2PVUOcF8YHGBXRrmtoskHehmzYJ"

  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  
  REDIS_PASSWORD: ""