apiVersion: v1
kind: Secret
metadata:
  name: sfa-secret
  namespace: sfa
type: Opaque
stringData:
  APP_KEY: "base64:6DxwTaX1yeG7JfY42Rs8ibC8hbSCRlGoPkXIsUQ0KVk="
  JWT_SECRET: "vdiWdydatGmN7t0JvVzX0ICPaIA2bGxMKG0Jc2PVUOcF8YHGBXRrmtoskHehmzYJ"

  DB_USERNAME: "sfa"
  DB_PASSWORD: "sfa@123"
  ROOT_PASSWORD: "4BEh4P+]p$X-+yz^"
  
  REDIS_PASSWORD: ""